export const BREAKING_NEWS_LOADING = 'BREAKING_NEWS_LOADING';
export const BREAKING_NEWS_SUCCESS = 'BREAKING_NEWS_SUCCESS';
export const BREAKING_NEWS_FAIL = 'BREAKING_NEWS_FAIL';

export const TECH_NEWS_LOADING = 'TECH_NEWS_LOADING';
export const TECH_NEWS_SUCCESS = 'TECH_NEWS_SUCCESS';
export const TECH_NEWS_FAIL = 'TECH_NEWS_FAIL';

export const POLITICAL_NEWS_LOADING = 'POLITICAL_NEWS_LOADING';
export const POLITICAL_NEWS_SUCCESS = 'POLITICAL_NEWS_SUCCESS';
export const POLITICAL_NEWS_FAIL = 'POLITICAL_NEWS_FAIL';

export const ENTERTAINMENT_NEWS_LOADING = 'ENTERTAINMENT_NEWS_LOADING';
export const ENTERTAINMENT_NEWS_SUCCESS = 'ENTERTAINMENT_NEWS_SUCCESS';
export const ENTERTAINMENT_NEWS_FAIL = 'ENTERTAINMENT_NEWS_FAIL';

export const GENERAL_NEWS_LOADING = 'GENERAL_NEWS_LOADING';
export const GENERAL_NEWS_SUCCESS = 'GENERAL_NEWS_SUCCESS';
export const GENERAL_NEWS_FAIL = 'GENERAL_NEWS_FAIL';
