export const BREAKING_NEWS_LOADING = 'BREAKING_NEWS_LOADING';
export const BREAKING_NEWS_SUCCESS = 'BREAKING_NEWS_SUCCESS';
export const BREAKING_NEWS_FAIL = 'BREAKING_NEWS_FAIL';

export const TECH_NEWS_LOADING = 'TECH_NEWS_LOADING';
export const TECH_NEWS_SUCCESS = 'TECH_NEWS_SUCCESS';
export const TECH_NEWS_FAIL = 'TECH_NEWS_FAIL';

export const HEALTH_NEWS_LOADING = 'HEALTH_NEWS_LOADING';
export const HEALTH_NEWS_SUCCESS = 'HEALTH_NEWS_SUCCESS';
export const HEALTH_NEWS_FAIL = 'HEALTH_NEWS_FAIL';

export const ENTERTAINMENT_NEWS_LOADING = 'ENTERTAINMENT_NEWS_LOADING';
export const ENTERTAINMENT_NEWS_SUCCESS = 'ENTERTAINMENT_NEWS_SUCCESS';
export const ENTERTAINMENT_NEWS_FAIL = 'ENTERTAINMENT_NEWS_FAIL';

export const LATEST_NEWS_LOADING = 'LATEST_NEWS_LOADING';
export const LATEST_NEWS_SUCCESS = 'LATEST_NEWS_SUCCESS';
export const LATEST_NEWS_FAIL = 'LATEST_NEWS_FAIL';
